CREATE TABLE `insurance_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`proposalId` int NOT NULL,
	`optIn` int DEFAULT 0,
	`txid` varchar(30),
	`pixPayload` text,
	`amount` decimal(10,2) DEFAULT '19.00',
	`status` enum('PENDING','PAID','EXPIRED') NOT NULL DEFAULT 'PENDING',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `insurance_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `proposals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`term` int NOT NULL,
	`monthlyRate` decimal(6,4),
	`cetAnnual` decimal(6,2),
	`installment` decimal(10,2),
	`fullName` varchar(255),
	`phone` varchar(20),
	`email` varchar(320),
	`whatsappOptIn` int DEFAULT 0,
	`cpf` varchar(14),
	`birthDate` varchar(10),
	`cep` varchar(10),
	`street` varchar(255),
	`number` varchar(20),
	`complement` varchar(100),
	`neighborhood` varchar(100),
	`city` varchar(100),
	`state` varchar(2),
	`creditCheckConsent` int DEFAULT 0,
	`incomeRange` varchar(50),
	`occupation` varchar(100),
	`loanPurpose` varchar(100),
	`termsAccepted` int DEFAULT 0,
	`truthDeclaration` int DEFAULT 0,
	`status` enum('draft','submitted','analyzing','approved','rejected') NOT NULL DEFAULT 'draft',
	`currentStep` int DEFAULT 1,
	`utmSource` varchar(255),
	`utmMedium` varchar(255),
	`utmCampaign` varchar(255),
	`utmContent` varchar(255),
	`utmTerm` varchar(255),
	`honeypot` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `proposals_id` PRIMARY KEY(`id`)
);
